import { PETWASH_LOGO_BASE64 } from './logo-base64';
import { SUPPORT_EMAIL } from '../../../shared/support-contact';
import { BRAND_NAME, LEGAL_NAME_HE, LEGAL_NAME_EN, COMPANY_TAX_ID } from '../brand-identity';

// ============================================================
// PetWash™ — Service Completed + Review Request 2026
// Sent: ~1 hour after service marked complete
// Triggers review, loyalty points summary, next booking CTA
// Brand: Black · Gold · White | NO PURPLE | Bilingual HE+EN
// ============================================================

export interface ServiceCompletedParams {
    language: 'en' | 'he';
    bookingRef: string;
    customerName: string;
    firstName: string;
    providerName: string;
    providerAvatar?: string;    // URL to provider photo
  serviceLabel: string;
    serviceIcon: string;
    petName: string;
    petBreed?: string;
    dateFormatted: string;
    durationMinutes?: number;
    priceFormatted: string;
    loyaltyPointsEarned: number;
    loyaltyTotalPoints: number;
    loyaltyTier: string;        // e.g. "Gold", "זהב"
  reviewUrl: string;
    bookAgainUrl: string;
    dashboardUrl: string;
    nextServiceSuggestion?: string;   // e.g. "Book next wash in 4 weeks"
  receiptUrl?: string;
}

export function buildServiceCompletedEmail(p: ServiceCompletedParams): string {
    const isHe = p.language === 'he';
    const dir = isHe ? 'rtl' : 'ltr';
    const align = isHe ? 'right' : 'left';
    const year = new Date().getFullYear();

  const t = {
        preheader: isHe
          ? `תודה ${p.firstName}! ${p.serviceLabel} ל${p.petName} הושלם. השאירו ביקורת`
                : `Thank you ${p.firstName}! ${p.serviceLabel} for ${p.petName} is complete. Leave a review`,
        headline: isHe ? `${p.serviceLabel} הושלם! 🎉` : `${p.serviceLabel} Complete! 🎉`,
        sub: isHe
          ? `תודה שבחרתם ב-${BRAND_NAME}`
                : `Thank you for choosing ${BRAND_NAME}`,
        summary: isHe ? 'סיכום השירות' : 'Service Summary',
        provider: isHe ? 'ניתן על ידי' : 'Provided by',
        pet: isHe ? 'חיית המחמד' : 'Pet',
        date: isHe ? 'תאריך' : 'Date',
        duration: isHe ? 'משך השירות' : 'Duration',
        total: isHe ? 'סה"כ שולם' : 'Total Paid',
        loyaltyTitle: isHe ? 'נקודות נאמנות' : 'Loyalty Points',
        loyaltyEarned: isHe ? `+${p.loyaltyPointsEarned} נקודות הוספו` : `+${p.loyaltyPointsEarned} points earned`,
        loyaltyBalance: isHe ? `יתרה: ${p.loyaltyTotalPoints} נקודות` : `Balance: ${p.loyaltyTotalPoints} points`,
        loyaltyTier: isHe ? `רמה: ${p.loyaltyTier}` : `Tier: ${p.loyaltyTier}`,
        reviewTitle: isHe ? 'איך היה?' : 'How was it?',
        reviewSub: isHe
          ? `הביקורת שלכם עוזרת ל${p.providerName} ולספקים שלנו לצמוח`
                : `Your review helps ${p.providerName} and our providers grow`,
        stars: ['⭐', '⭐⭐', '⭐⭐⭐', '⭐⭐⭐⭐', '⭐⭐⭐⭐⭐'],
        reviewBtn: isHe ? 'כתבו ביקורת' : 'Leave a Review',
        bookAgain: isHe ? 'הזמינו שוב' : 'Book Again',
        receipt: isHe ? 'הורד קבלה' : 'Download Receipt',
        nextService: isHe ? 'המלצה הבאה' : 'Next Recommendation',
        footer1: isHe ? 'שאלות? אנחנו כאן' : 'Questions? We\'re here',
  };

  const starRatingRow = (url: string) => `
      <table cellpadding="0" cellspacing="0" border="0" style="margin:16px auto 0;">
            <tr>
                    ${[1,2,3,4,5].map(n => `
                            <td style="padding:0 4px;">
                                      <a href="${url}?rating=${n}" style="display:block;font-size:28px;text-decoration:none;line-height:1;">⭐</a>
                                              </td>`).join('')}
                                                    </tr>
                                                        </table>
                                                          `;

  return `<!DOCTYPE html>
  <html dir="${dir}" lang="${p.language}">
  <head>
    <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width,initial-scale=1.0" />
        <title>${t.headline}</title>
          <style>
              @media only screen and (max-width:600px){ .pw-wrap{width:100%!important;} }
                </style>
                </head>
                <body style="margin:0;padding:0;background:#f5f5f0;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;">
                <span style="display:none;max-height:0;overflow:hidden;">${t.preheader}</span>

                <table width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#f5f5f0;">
                <tr><td align="center" style="padding:32px 16px;">
                <table class="pw-wrap" width="600" cellpadding="0" cellspacing="0" border="0"
                  style="background:#fff;box-shadow:0 2px 16px rgba(0,0,0,.08);">

                    <!-- SUCCESS BANNER -->
                      <tr>
                          <td style="background:#1a7a4a;padding:10px 40px;text-align:center;">
                                <span style="color:#fff;font-size:12px;font-weight:700;letter-spacing:2px;text-transform:uppercase;">
                                        ✅ ${isHe ? 'שירות הושלם בהצלחה' : 'SERVICE COMPLETED SUCCESSFULLY'}
                                              </span>
                                                  </td>
                                                    </tr>

                                                      <!-- HEADER -->
                                                        <tr>
                                                            <td style="background:#0a0a0a;padding:36px 40px 28px;text-align:center;">
                                                                  <img src="${PETWASH_LOGO_BASE64}" alt="${BRAND_NAME}" width="120"
                                                                          style="display:block;margin:0 auto 16px;width:120px;height:auto;" />
                                                                                <div style="font-size:36px;margin-bottom:8px;">🐾</div>
                                                                                      <h1 style="margin:0;color:#C9A96E;font-size:22px;font-weight:700;">${t.headline}</h1>
                                                                                            <p style="margin:8px 0 0;color:#999;font-size:14px;">${t.sub}</p>
                                                                                                </td>
                                                                                                  </tr>

                                                                                                    <!-- PROVIDER CARD -->
                                                                                                      <tr>
                                                                                                          <td style="padding:28px 40px 0;">
                                                                                                                <div style="background:#f8f6f0;border:1px solid #e8e4d8;padding:20px;text-align:${align};display:flex;align-items:center;gap:16px;">
                                                                                                                        ${p.providerAvatar ? `<img src="${p.providerAvatar}" width="56" height="56"
                                                                                                                                  style="width:56px;height:56px;border-radius:50%;object-fit:cover;border:2px solid #C9A96E;" />` : ''}
                                                                                                                                          <div>
                                                                                                                                                    <p style="margin:0;font-size:11px;color:#C9A96E;font-weight:700;letter-spacing:2px;text-transform:uppercase;">
                                                                                                                                                                ${t.provider}
                                                                                                                                                                          </p>
                                                                                                                                                                                    <p style="margin:4px 0 0;font-size:16px;font-weight:600;color:#1a1a1a;">${p.providerName}</p>
                                                                                                                                                                                              <p style="margin:2px 0 0;font-size:13px;color:#888;">${p.serviceLabel} &bull; ${p.petName}</p>
                                                                                                                                                                                                      </div>
                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                </td>
                                                                                                                                                                                                                  </tr>
                                                                                                                                                                                                                  
                                                                                                                                                                                                                    <!-- SERVICE SUMMARY -->
                                                                                                                                                                                                                      <tr>
                                                                                                                                                                                                                          <td style="padding:24px 40px 20px;">
                                                                                                                                                                                                                                <h2 style="margin:0 0 16px;font-size:13px;font-weight:700;color:#1a1a1a;letter-spacing:2px;
                                                                                                                                                                                                                                        text-transform:uppercase;border-bottom:1px solid #e8e4d8;padding-bottom:10px;">${t.summary}</h2>
                                                                                                                                                                                                                                              <table width="100%" cellpadding="0" cellspacing="0" border="0">
                                                                                                                                                                                                                                                      <tr>
                                                                                                                                                                                                                                                                <td style="padding:8px 0;border-bottom:1px solid #f5f2ea;color:#999;font-size:12px;
                                                                                                                                                                                                                                                                            text-transform:uppercase;letter-spacing:1px;width:38%;text-align:${align};">${t.date}</td>
                                                                                                                                                                                                                                                                                      <td style="padding:8px 0;border-bottom:1px solid #f5f2ea;color:#1a1a1a;font-size:13px;
                                                                                                                                                                                                                                                                                                  font-weight:600;text-align:${align};">${p.dateFormatted}</td>
                                                                                                                                                                                                                                                                                                          </tr>
                                                                                                                                                                                                                                                                                                                  ${p.durationMinutes ? `<tr>
                                                                                                                                                                                                                                                                                                                            <td style="padding:8px 0;border-bottom:1px solid #f5f2ea;color:#999;font-size:12px;
                                                                                                                                                                                                                                                                                                                                        text-transform:uppercase;letter-spacing:1px;text-align:${align};">${t.duration}</td>
                                                                                                                                                                                                                                                                                                                                                  <td style="padding:8px 0;border-bottom:1px solid #f5f2ea;color:#1a1a1a;font-size:13px;
                                                                                                                                                                                                                                                                                                                                                              font-weight:600;text-align:${align};">${p.durationMinutes} min</td>
                                                                                                                                                                                                                                                                                                                                                                      </tr>` : ''}
                                                                                                                                                                                                                                                                                                                                                                              <tr>
                                                                                                                                                                                                                                                                                                                                                                                        <td style="padding:8px 0;color:#999;font-size:12px;text-transform:uppercase;
                                                                                                                                                                                                                                                                                                                                                                                                    letter-spacing:1px;text-align:${align};">${t.total}</td>
                                                                                                                                                                                                                                                                                                                                                                                                              <td style="padding:8px 0;color:#1a1a1a;font-size:16px;font-weight:700;
                                                                                                                                                                                                                                                                                                                                                                                                                          text-align:${align};">${p.priceFormatted}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                  </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                              ${p.receiptUrl ? `<a href="${p.receiptUrl}" style="display:inline-block;margin-top:12px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                      color:#888;font-size:12px;text-decoration:underline;">${t.receipt}</a>` : ''}
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <!-- LOYALTY POINTS CARD -->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td style="padding:0 40px 24px;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style="background:linear-gradient(135deg,#0a0a0a 0%,#1a1a1a 100%);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding:20px 24px;text-align:center;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p style="margin:0 0 6px;font-size:11px;color:#C9A96E;font-weight:700;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    letter-spacing:3px;text-transform:uppercase;">${t.loyaltyTitle}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p style="margin:0;font-size:24px;font-weight:700;color:#C9A96E;">${t.loyaltyEarned}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p style="margin:6px 0 0;font-size:13px;color:#888;">${t.loyaltyBalance} &bull; ${t.loyaltyTier}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <!-- DIVIDER -->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <tr><td style="height:1px;background:linear-gradient(90deg,transparent,#e8e4d8,transparent);"></td></tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <!-- REVIEW REQUEST -->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <td style="padding:28px 40px 8px;text-align:center;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h2 style="margin:0 0 6px;font-size:18px;font-weight:700;color:#1a1a1a;">${t.reviewTitle}</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p style="margin:0;font-size:14px;color:#666;line-height:1.6;">${t.reviewSub}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ${starRatingRow(p.reviewUrl)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a href="${p.reviewUrl}" style="display:inline-block;margin-top:20px;background:#1a1a1a;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color:#C9A96E;text-decoration:none;padding:14px 40px;font-size:12px;font-weight:700;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    letter-spacing:2px;text-transform:uppercase;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ${t.reviewBtn}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <!-- NEXT SERVICE SUGGESTION -->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ${p.nextServiceSuggestion ? `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <td style="padding:20px 40px;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style="background:#f0faf5;border:1px solid #1a7a4a;padding:14px 20px;text-align:center;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p style="margin:0;font-size:13px;color:#1a7a4a;font-weight:600;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          💡 ${t.nextService}: ${p.nextServiceSuggestion}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </tr>` : ''}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <!-- BOOK AGAIN -->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <td style="padding:8px 40px 32px;text-align:center;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="${p.bookAgainUrl}" style="display:inline-block;background:#1a7a4a;color:#fff;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    text-decoration:none;padding:13px 32px;font-size:12px;font-weight:700;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            letter-spacing:2px;text-transform:uppercase;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    🔄 ${t.bookAgain}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <!-- FOOTER -->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <tr><td style="height:1px;background:linear-gradient(90deg,transparent,#e8e4d8,transparent);"></td></tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <td style="background:#0a0a0a;padding:20px 40px;text-align:center;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p style="margin:0 0 4px;color:#666;font-size:12px;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ${t.footer1}: <a href="mailto:${SUPPORT_EMAIL}" style="color:#C9A96E;text-decoration:none;">${SUPPORT_EMAIL}</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p style="margin:0;color:#444;font-size:11px;">${BRAND_NAME} | ${LEGAL_NAME_HE} | ${LEGAL_NAME_EN} | ח.פ. ${COMPANY_TAX_ID} | © ${year}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </td></tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </html>`;
}
