/**
 * PetWash™ Universal Pass Distribution — 2026
 *
 * All distribution routes accept a SIGNED wallet-link token (not a plain passId).
 * Tokens are generated by buildPassLinkToken() in server/lib/passTokens.ts.
 * Tokens expire in 72 hours and contain the passId + purpose:'wallet-link'.
 *
 * Routes mounted at /api/pass:
 *
 *   GET /api/pass/:signedToken           — UA-detect → Apple / Google / HTML chooser
 *   GET /api/pass/apple/:signedToken     — Serve .pkpass file
 *   GET /api/pass/google/:signedToken    — Redirect to Google Wallet save URL
 *
 * Apple update web service (webServiceURL = BASE_URL/api/pass/apple):
 *   POST   /api/pass/apple/v1/devices/:did/registrations/:ptid/:serial — Register device
 *   DELETE /api/pass/apple/v1/devices/:did/registrations/:ptid/:serial — Unregister device
 *   GET    /api/pass/apple/v1/devices/:did/registrations/:ptid         — List registered passes
 *   GET    /api/pass/apple/v1/passes/:ptid/:serial                     — Serve updated pass
 *   POST   /api/pass/apple/v1/log                                      — Apple error log endpoint
 */

import { Router, Request, Response } from 'express';
import { db } from '../db';
import { petwashPassAccounts, appleWalletDeviceRegistrations } from '@shared/schema';
import { eq, and } from 'drizzle-orm';
import { logger } from '../lib/logger';
import {
  verifyPassLinkToken,
  verifyApplePassAuthToken,
} from '../lib/passTokens';
import {
  generateAppleWalletPass,
  buildPassJson as applePassJson,
  isAppleWalletConfigured,
} from '../services/AppleWalletService';
import {
  buildSaveUrl as googleBuildSaveUrl,
  isGoogleWalletConfigured,
} from '../services/GoogleWalletService';

const router = Router();

// ─── Helpers ──────────────────────────────────────────────────────────────────

function isIOS(ua: string): boolean {
  return /iphone|ipad|ipod/i.test(ua) || (/macintosh/i.test(ua) && /safari/i.test(ua) && !/android/i.test(ua));
}
function isAndroid(ua: string): boolean {
  return /android/i.test(ua);
}

async function lookupPassByToken(token: string) {
  const payload = verifyPassLinkToken(token);                     // throws on bad/expired token
  const [pass]  = await db
    .select()
    .from(petwashPassAccounts)
    .where(eq(petwashPassAccounts.passId, payload.passId))
    .limit(1);
  return pass && pass.status === 'ACTIVE' ? pass : null;
}

async function lookupActivePassBySerial(serialNumber: string) {
  const [pass] = await db
    .select()
    .from(petwashPassAccounts)
    .where(eq(petwashPassAccounts.passId, serialNumber))
    .limit(1);
  return pass && pass.status === 'ACTIVE' ? pass : null;
}

function applePassAuthToken(req: Request): string {
  const header = req.header('authorization') || req.header('Authorization') || '';
  return header.startsWith('ApplePass ') ? header.slice('ApplePass '.length).trim() : '';
}

function verifyApplePassRequest(req: Request, pass: typeof petwashPassAccounts.$inferSelect): boolean {
  try {
    return verifyApplePassAuthToken(
      applePassAuthToken(req),
      pass.passId,
      pass.userId,
      pass.qrTokenVersion,
    );
  } catch {
    return false;
  }
}

function buildVisual(pass: typeof petwashPassAccounts.$inferSelect) {
  return {
    passId:             pass.passId,
    userId:             pass.userId,
    ownerName:          pass.ownerName,
    primaryPetName:     pass.primaryPetName ?? undefined,
    tier:               pass.tier,
    availableCreditIls: Number(pass.availableCreditIls),
    validUntil:         pass.validUntil?.toISOString().split('T')[0] ?? undefined,
    qrTokenVersion:     pass.qrTokenVersion,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// GET /api/pass/:signedToken — Universal distribution link
// Detects user-agent: iOS → Apple Wallet, Android → Google Wallet, desktop → chooser
// ─────────────────────────────────────────────────────────────────────────────
router.get('/:token', async (req: Request, res: Response) => {
  try {
    const pass = await lookupPassByToken(req.params.token);
    if (!pass) return res.status(404).send('<h2>Pass not found or link expired</h2>');

    const ua  = req.headers['user-agent'] || '';
    const enc = encodeURIComponent(req.params.token);

    if (isIOS(ua) && isAppleWalletConfigured()) {
      return res.redirect(307, `/api/pass/apple/${enc}`);
    }
    if (isAndroid(ua) && isGoogleWalletConfigured()) {
      return res.redirect(307, `/api/pass/google/${enc}`);
    }

    const appleUrl  = `/api/pass/apple/${enc}`;
    const googleUrl = `/api/pass/google/${enc}`;
    const isHe      = (req.headers['accept-language'] || '').startsWith('he');

    const appleConfigured  = isAppleWalletConfigured();
    const googleConfigured = isGoogleWalletConfigured();

    res.setHeader('Content-Type', 'text/html; charset=utf-8');
    return res.send(`<!DOCTYPE html>
<html lang="${isHe ? 'he' : 'en'}" dir="${isHe ? 'rtl' : 'ltr'}">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>PetWash™ Pass</title>
<style>
  body{margin:0;background:#fff;font-family:'Helvetica Neue',Arial,sans-serif;display:flex;align-items:center;justify-content:center;min-height:100vh}
  .card{max-width:400px;width:90%;text-align:center;padding:40px 24px}
  .brand{font-size:11px;letter-spacing:6px;color:#C6A35B;text-transform:uppercase;margin-bottom:16px}
  h1{font-size:20px;color:#111;margin:0 0 6px}
  p{color:#888;font-size:14px;margin:0 0 32px}
  .btn{display:block;padding:16px 24px;border-radius:14px;text-decoration:none;font-size:15px;font-weight:600;margin-bottom:14px}
  .apple{background:#000;color:#fff}
  .google{background:#1a73e8;color:#fff}
  .disabled{background:#f5f5f5;color:#bbb;cursor:not-allowed}
  .id{font-size:11px;color:#ddd;margin-top:24px;letter-spacing:2px}
</style>
</head>
<body>
<div class="card">
  <div class="brand">P E T W A S H ™</div>
  <h1>${isHe ? 'הפאס הפרסטיז שלך' : 'Your Prestige Pass'}</h1>
  <p>${pass.ownerName}${pass.primaryPetName ? ' · ' + pass.primaryPetName + ' 🐾' : ''}</p>
  ${appleConfigured
    ? `<a class="btn apple" href="${appleUrl}">${isHe ? 'הוסף ל‑Apple Wallet' : 'Add to Apple Wallet'}</a>`
    : `<div class="btn disabled">${isHe ? 'Apple Wallet — בקרוב' : 'Apple Wallet — Coming Soon'}</div>`}
  ${googleConfigured
    ? `<a class="btn google" href="${googleUrl}">${isHe ? 'הוסף ל‑Google Wallet' : 'Add to Google Wallet'}</a>`
    : `<div class="btn disabled">${isHe ? 'Google Wallet — בקרוב' : 'Google Wallet — Coming Soon'}</div>`}
  <div class="id">${pass.passId}</div>
</div>
</body>
</html>`);
  } catch (err: any) {
    const msg = err?.message || '';
    if (msg === 'TOKEN_EXPIRED')               return res.status(410).send('<h2>Link expired — please request a new one from the PetWash app</h2>');
    if (msg === 'INVALID_SIGNATURE')           return res.status(403).send('<h2>Invalid link</h2>');
    if (msg === 'INVALID_TOKEN_FORMAT')        return res.status(403).send('<h2>Invalid link</h2>');
    if (msg === 'INVALID_PURPOSE')             return res.status(403).send('<h2>Invalid link</h2>');
    if (msg === 'TOKEN_SECRET_NOT_CONFIGURED') return res.status(503).json({ ok: false, error: 'PASS_LINK_SECRET not configured on server' });
    logger.error('[PassUniversal] Universal link error', { err });
    return res.status(500).send('Internal error');
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// GET /api/pass/apple/:signedToken — Serve signed .pkpass file
// ─────────────────────────────────────────────────────────────────────────────
router.get('/apple/:token', async (req: Request, res: Response) => {
  try {
    if (!isAppleWalletConfigured()) {
      const preview = applePassJson({
        passId: 'PREVIEW', userId: 'PREVIEW', ownerName: 'Member',
        tier: 'PREMIUM', availableCreditIls: 0, qrTokenVersion: 1,
      });
      return res.status(503).json({ ok: false, error: 'Apple Wallet certificates not yet configured', preview });
    }

    const pass = await lookupPassByToken(req.params.token);
    if (!pass) return res.status(404).json({ ok: false, error: 'Pass not found or link expired' });

    const pkpassBuffer = await generateAppleWalletPass(buildVisual(pass));

    res.setHeader('Content-Type', 'application/vnd.apple.pkpass');
    res.setHeader('Content-Disposition', `attachment; filename="${pass.passId}.pkpass"`);
    res.setHeader('Last-Modified', new Date().toUTCString());
    return res.send(pkpassBuffer);
  } catch (err: any) {
    if (err?.message === 'TOKEN_EXPIRED') return res.status(410).json({ ok: false, error: 'Link expired' });
    logger.error('[PassUniversal] Apple pkpass error', { err });
    return res.status(500).json({ ok: false, error: 'Pass generation failed' });
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// GET /api/pass/google/:signedToken — Redirect to Google Wallet save URL
// ─────────────────────────────────────────────────────────────────────────────
router.get('/google/:token', async (req: Request, res: Response) => {
  try {
    if (!isGoogleWalletConfigured()) {
      return res.status(503).json({ ok: false, error: 'Google Wallet not yet configured — set GOOGLE_WALLET_ISSUER_ID and GOOGLE_WALLET_SA_KEY' });
    }

    const pass = await lookupPassByToken(req.params.token);
    if (!pass) return res.status(404).json({ ok: false, error: 'Pass not found or link expired' });

    const saveUrl = googleBuildSaveUrl(buildVisual(pass));
    if (!saveUrl) return res.status(503).json({ ok: false, error: 'Could not generate Google Wallet URL' });

    return res.redirect(307, saveUrl);
  } catch (err: any) {
    if (err?.message === 'TOKEN_EXPIRED') return res.status(410).json({ ok: false, error: 'Link expired' });
    logger.error('[PassUniversal] Google wallet redirect error', { err });
    return res.status(500).json({ ok: false, error: 'Internal error' });
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// Apple Wallet Update Web Service
// Apple devices call these endpoints when the pass is added / updated.
// Spec: https://developer.apple.com/documentation/walletpasses/adding_a_web_service_to_update_passes
// ─────────────────────────────────────────────────────────────────────────────

// POST /api/pass/apple/v1/devices/:did/registrations/:ptid/:serial — Register device
router.post('/apple/v1/devices/:deviceId/registrations/:passTypeId/:serialNumber', async (req: Request, res: Response) => {
  try {
    const { deviceId, serialNumber } = req.params;
    const pushToken = req.body?.pushToken;
    if (!pushToken) return res.status(400).send();
    const pass = await lookupActivePassBySerial(serialNumber);
    if (!pass) return res.status(404).send();
    if (!verifyApplePassRequest(req, pass)) return res.status(401).send();

    await db.insert(appleWalletDeviceRegistrations)
      .values({
        deviceLibraryIdentifier: deviceId,
        pushToken,
        passTypeIdentifier:      req.params.passTypeId,
        serialNumber,
      })
      .onConflictDoUpdate({
        target: [
          appleWalletDeviceRegistrations.deviceLibraryIdentifier,
          appleWalletDeviceRegistrations.serialNumber,
        ],
        set: { pushToken },
      });

    logger.info('[AppleWallet] Device registered', { deviceId, serialNumber });
    return res.status(201).send();
  } catch (err) {
    logger.error('[AppleWallet] Device registration error', { err });
    return res.status(500).send();
  }
});

// DELETE /api/pass/apple/v1/devices/:did/registrations/:ptid/:serial — Unregister device
router.delete('/apple/v1/devices/:deviceId/registrations/:passTypeId/:serialNumber', async (req: Request, res: Response) => {
  try {
    const { deviceId, serialNumber } = req.params;
    const pass = await lookupActivePassBySerial(serialNumber);
    if (!pass) return res.status(404).send();
    if (!verifyApplePassRequest(req, pass)) return res.status(401).send();

    await db.delete(appleWalletDeviceRegistrations).where(
      and(
        eq(appleWalletDeviceRegistrations.deviceLibraryIdentifier, deviceId),
        eq(appleWalletDeviceRegistrations.serialNumber, serialNumber),
      ),
    );
    logger.info('[AppleWallet] Device unregistered', { deviceId, serialNumber });
    return res.status(200).send();
  } catch (err) {
    logger.error('[AppleWallet] Device unregister error', { err });
    return res.status(500).send();
  }
});

// GET /api/pass/apple/v1/devices/:did/registrations/:ptid — List passes for device
router.get('/apple/v1/devices/:deviceId/registrations/:passTypeId', async (req: Request, res: Response) => {
  try {
    const regs = await db
      .select({ serialNumber: appleWalletDeviceRegistrations.serialNumber })
      .from(appleWalletDeviceRegistrations)
      .where(eq(appleWalletDeviceRegistrations.deviceLibraryIdentifier, req.params.deviceId));

    if (!regs.length) return res.status(204).send();

    return res.json({
      serialNumbers: regs.map(r => r.serialNumber),
      lastUpdated:   new Date().toISOString(),
    });
  } catch (err) {
    logger.error('[AppleWallet] Registration list error', { err });
    return res.status(500).send();
  }
});

// GET /api/pass/apple/v1/passes/:ptid/:serial — Serve updated pass to Apple
router.get('/apple/v1/passes/:passTypeId/:serialNumber', async (req: Request, res: Response) => {
  try {
    if (!isAppleWalletConfigured()) return res.status(503).send();

    const { serialNumber } = req.params;
    const pass = await lookupActivePassBySerial(serialNumber);

    if (!pass) return res.status(404).send();
    if (!verifyApplePassRequest(req, pass)) return res.status(401).send();

    // Honour If-Modified-Since (Apple skips download if pass hasn't changed)
    const ifModSince = req.headers['if-modified-since'];
    if (ifModSince && pass.updatedAt && new Date(ifModSince) >= new Date(pass.updatedAt)) {
      return res.status(304).send();
    }

    const pkpassBuffer = await generateAppleWalletPass(buildVisual(pass));

    res.setHeader('Content-Type', 'application/vnd.apple.pkpass');
    res.setHeader('Last-Modified', new Date().toUTCString());
    return res.send(pkpassBuffer);
  } catch (err) {
    logger.error('[AppleWallet] Pass update serve error', { err });
    return res.status(500).send();
  }
});

// POST /api/pass/apple/v1/log — Apple logs errors from device
router.post('/apple/v1/log', (req: Request, res: Response) => {
  const logs = req.body?.logs || [];
  logs.forEach((entry: string) => logger.warn('[AppleWallet:Device]', { entry }));
  return res.status(200).send();
});

export default router;
