/**
 * A wallet button is offered only when that rail can serve a pass
 * — regression pin (2026-09-19).
 *
 * Reported live from an iPhone: "apple wallet pass cannot be download to
 * iphone... did all codes, no done".
 *
 * The cause was not in the download path. /api/pass/apple/:token answers 503
 * when the PassKit certificates are not installed (isAppleWalletConfigured()
 * is false), and those certificates cannot be generated by the deploy — unlike
 * PASS_LINK_SECRET and PRESTIGE_QR_SECRET, which petwash-ci.yml creates with
 * `ensure_secret`, the Apple credentials must be uploaded by a human from the
 * Apple Developer portal. Until that happens the rail cannot work at all.
 *
 * The defect this pins is what the product did about it: PrestigePassWallet
 * rendered a live black "Add to Apple Wallet" button regardless, so the member
 * got a dead tap and no reason. /api/pass/:token's own fallback page has
 * always told the truth in that state — it renders "Apple Wallet — בקרוב" —
 * so the wallet page now says the same thing.
 *
 * Source-level pins: this needs Firestore + Firebase auth + Postgres to render,
 * so the pins assert the contract on both sides rather than standing that up.
 */
import fs from 'node:fs';
import path from 'node:path';
import { describe, it, expect } from 'vitest';

const ROOT = path.resolve(__dirname, '..', '..', '..');
const PAGE = fs.readFileSync(
  path.join(ROOT, 'client', 'src', 'pages', 'PrestigePassWallet.tsx'),
  'utf8',
);
const ROUTE = fs.readFileSync(
  path.join(ROOT, 'server', 'routes', 'prestige-pass.ts'),
  'utf8',
);

describe('wallet buttons reflect what the server can actually serve (2026-09-19)', () => {
  it('the server reports which rails are configured', () => {
    expect(ROUTE).toMatch(/walletProviders:\s*\{/);
    expect(ROUTE).toMatch(/apple:\s*isAppleWalletConfigured\(\)/);
    expect(ROUTE).toMatch(/google:\s*isGoogleWalletConfigured\(\)/);
  });

  it('it reports booleans only — never a certificate, key or env name', () => {
    const block = ROUTE.slice(
      ROUTE.indexOf('walletProviders: {'),
      ROUTE.indexOf('walletProviders: {') + 200,
    );
    expect(block).not.toMatch(/PEM|CERT|KEY|process\.env/);
  });

  it('the page offers a wallet button only when that rail is ready', () => {
    expect(PAGE).toMatch(/appleWalletReady\s*\?/);
    expect(PAGE).toMatch(/googleWalletReady\s*\?/);
    // and the mutation is reachable only from the ready branch
    const appleBranch = PAGE.slice(
      PAGE.indexOf('{appleWalletReady ?'),
      PAGE.indexOf('{googleWalletReady ?'),
    );
    expect(appleBranch).toMatch(/walletDownloadMutation\.mutate\('apple'\)/);
  });

  it('an unconfigured rail says "coming soon", matching the server fallback page', () => {
    expect(PAGE).toMatch(/Apple Wallet — בקרוב/);
    expect(PAGE).toMatch(/Apple Wallet — Coming Soon/);
    expect(PAGE).toMatch(/apple-wallet-coming-soon/);
  });

  it('it fails OPEN — only an explicit false hides a button', () => {
    // A server that predates this field, or a cached response, omits
    // walletProviders; that must not tell members "coming soon" about a rail
    // that works.
    expect(PAGE).toMatch(/walletProviders\?\.apple\s*!==\s*false/);
    expect(PAGE).toMatch(/walletProviders\?\.google\s*!==\s*false/);
  });
});
