import { db } from './db';
import { walkerProfiles } from '../shared/schema';
import crypto from 'crypto';

export const seedWalkers = async () => {
  console.log('[Seed] Creating 12 detailed walker profiles...');

  const walkers = [
    {
      walkerId: `WALKER-${crypto.randomUUID()}`,
      userId: `user-${Date.now()}-1`,
      firstName: 'David',
      lastName: 'Cohen',
      displayName: 'David C.',
      profilePhotoUrl: null,
      bio: 'Professional dog walker with 8 years of experience. Specialized in training reactive dogs and large breeds. I love spending time outdoors with dogs and building strong bonds. Certified in pet first aid and CPR. Available for jogging runs and off-leash adventures in approved parks.',
      city: 'Tel Aviv',
      country: 'Israel',
      currentLatitude: '32.0853',
      currentLongitude: '34.7818',
      emergencyContactName: 'Sarah Cohen',
      emergencyContactPhone: '+972501234567',
      languagesSpoken: ['Hebrew', 'English'],
      experienceYears: 8,
      petSizesHandled: ['Small (0-10kg)', 'Medium (10-25kg)', 'Large (25-45kg)', 'Giant (45kg+)'],
      specialties: ['Reactive Dogs', 'Multiple Dogs', 'Jogging/Running', 'Off-Leash'],
      certifications: ['Pet First Aid', 'Dog Behavior Specialist', 'Professional Dog Walker'],
      hasInsurance: true,
      insurancePolicyNumber: 'INS-2024-TEL-001',
      insuranceCoverageAmount: '2000000',
      verificationStatus: 'verified' as const,
      kycCompleted: true,
      kycVerifiedAt: new Date('2024-01-15'),
      averageRating: '4.95',
      totalWalks: 847,
      totalReviews: 253,
      acceptanceRate: '98.5',
      responseTimeMinutes: 8,
      onTimeRate: '99.2',
      baseHourlyRate: '85.00',
      currency: 'ILS',
      isAvailable: true,
      maxDailyWalks: 6,
      bankAccountVerified: true,
      commissionRate: '18.00',
      isActive: true,
      hasBodyCamera: true,
      hasDroneAccess: false,
      maxSimultaneousDogs: 3,
      createdAt: new Date('2023-06-12'),
      updatedAt: new Date(),
    },
    {
      walkerId: `WALKER-${crypto.randomUUID()}`,
      userId: `user-${Date.now()}-2`,
      firstName: 'Maya',
      lastName: 'Levi',
      displayName: 'Maya L.',
      profilePhotoUrl: null,
      bio: 'Passionate dog lover and experienced walker specializing in senior dogs and puppies. I provide gentle, caring walks with lots of patience. Former veterinary assistant with deep understanding of dog health and behavior. Love taking photos during walks!',
      city: 'Jerusalem',
      country: 'Israel',
      currentLatitude: '31.7683',
      currentLongitude: '35.2137',
      emergencyContactName: 'Dan Levi',
      emergencyContactPhone: '+972501234568',
      languagesSpoken: ['Hebrew', 'English', 'Russian'],
      experienceYears: 5,
      petSizesHandled: ['Small (0-10kg)', 'Medium (10-25kg)', 'Large (25-45kg)'],
      specialties: ['Senior Dogs', 'Puppy Training', 'Pet Medication'],
      certifications: ['Pet First Aid', 'Veterinary Assistant'],
      hasInsurance: true,
      insurancePolicyNumber: 'INS-2024-JER-002',
      insuranceCoverageAmount: '2000000',
      verificationStatus: 'verified' as const,
      kycCompleted: true,
      kycVerifiedAt: new Date('2024-02-20'),
      averageRating: '4.98',
      totalWalks: 523,
      totalReviews: 189,
      acceptanceRate: '97.0',
      responseTimeMinutes: 12,
      onTimeRate: '98.5',
      baseHourlyRate: '75.00',
      currency: 'ILS',
      isAvailable: true,
      maxDailyWalks: 5,
      bankAccountVerified: true,
      commissionRate: '18.00',
      isActive: true,
      hasBodyCamera: true,
      hasDroneAccess: false,
      maxSimultaneousDogs: 2,
      createdAt: new Date('2023-09-05'),
      updatedAt: new Date(),
    },
    {
      walkerId: `WALKER-${crypto.randomUUID()}`,
      userId: `user-${Date.now()}-3`,
      firstName: 'Yoni',
      lastName: 'Peretz',
      displayName: 'Yoni P.',
      profilePhotoUrl: null,
      bio: 'High-energy walker perfect for active breeds! I love running with dogs and exploring new trails. Experienced with high-energy breeds like Huskies, Border Collies, and German Shepherds. Weekend hiking trips available. GPS tracking and live updates guaranteed.',
      city: 'Haifa',
      country: 'Israel',
      currentLatitude: '32.7940',
      currentLongitude: '34.9896',
      emergencyContactName: 'Rachel Peretz',
      emergencyContactPhone: '+972501234569',
      languagesSpoken: ['Hebrew', 'English'],
      experienceYears: 6,
      petSizesHandled: ['Medium (10-25kg)', 'Large (25-45kg)', 'Giant (45kg+)'],
      specialties: ['Jogging/Running', 'Off-Leash', 'Multiple Dogs'],
      certifications: ['Pet First Aid', 'Canine Fitness Trainer'],
      hasInsurance: true,
      insurancePolicyNumber: 'INS-2024-HFA-003',
      insuranceCoverageAmount: '2000000',
      verificationStatus: 'verified' as const,
      kycCompleted: true,
      kycVerifiedAt: new Date('2024-01-10'),
      averageRating: '4.92',
      totalWalks: 612,
      totalReviews: 201,
      acceptanceRate: '96.5',
      responseTimeMinutes: 10,
      onTimeRate: '97.8',
      baseHourlyRate: '90.00',
      currency: 'ILS',
      isAvailable: true,
      maxDailyWalks: 7,
      bankAccountVerified: true,
      commissionRate: '18.00',
      isActive: true,
      hasBodyCamera: true,
      hasDroneAccess: true,
      maxSimultaneousDogs: 4,
      createdAt: new Date('2023-07-20'),
      updatedAt: new Date(),
    },
    {
      walkerId: `WALKER-${crypto.randomUUID()}`,
      userId: `user-${Date.now()}-4`,
      firstName: 'Noa',
      lastName: 'Mizrahi',
      displayName: 'Noa M.',
      profilePhotoUrl: null,
      bio: 'Gentle and caring walker specializing in anxious and fearful dogs. I use positive reinforcement techniques and create safe, stress-free walking experiences. Trained in dog psychology and behavior modification. Perfect for reactive or nervous dogs who need extra patience.',
      city: 'Tel Aviv',
      country: 'Israel',
      currentLatitude: '32.0853',
      currentLongitude: '34.7818',
      emergencyContactName: 'Avi Mizrahi',
      emergencyContactPhone: '+972501234570',
      languagesSpoken: ['Hebrew', 'English', 'French'],
      experienceYears: 7,
      petSizesHandled: ['Small (0-10kg)', 'Medium (10-25kg)', 'Large (25-45kg)'],
      specialties: ['Reactive Dogs', 'Puppy Training', 'Senior Dogs'],
      certifications: ['Pet First Aid', 'Dog Psychology Specialist', 'Behavior Modification'],
      hasInsurance: true,
      insurancePolicyNumber: 'INS-2024-TEL-004',
      insuranceCoverageAmount: '2000000',
      verificationStatus: 'verified' as const,
      kycCompleted: true,
      kycVerifiedAt: new Date('2023-12-05'),
      averageRating: '4.97',
      totalWalks: 734,
      totalReviews: 245,
      acceptanceRate: '98.0',
      responseTimeMinutes: 7,
      onTimeRate: '99.5',
      baseHourlyRate: '95.00',
      currency: 'ILS',
      isAvailable: true,
      maxDailyWalks: 5,
      bankAccountVerified: true,
      commissionRate: '18.00',
      isActive: true,
      hasBodyCamera: true,
      hasDroneAccess: false,
      maxSimultaneousDogs: 2,
      createdAt: new Date('2023-05-18'),
      updatedAt: new Date(),
    },
    {
      walkerId: `WALKER-${crypto.randomUUID()}`,
      userId: `user-${Date.now()}-5`,
      firstName: 'Eitan',
      lastName: 'Kaplan',
      displayName: 'Eitan K.',
      profilePhotoUrl: null,
      bio: 'Professional dog walker and trainer with military K9 experience. Specialized in obedience training during walks and working with protection breeds. Strong, reliable, and disciplined. Perfect for large, powerful dogs who need a firm handler.',
      city: 'Beersheba',
      country: 'Israel',
      currentLatitude: '31.2518',
      currentLongitude: '34.7913',
      emergencyContactName: 'Tamar Kaplan',
      emergencyContactPhone: '+972501234571',
      languagesSpoken: ['Hebrew', 'English', 'Arabic'],
      experienceYears: 10,
      petSizesHandled: ['Medium (10-25kg)', 'Large (25-45kg)', 'Giant (45kg+)'],
      specialties: ['Multiple Dogs', 'Off-Leash', 'Reactive Dogs'],
      certifications: ['Pet First Aid', 'K9 Handler', 'Professional Dog Trainer'],
      hasInsurance: true,
      insurancePolicyNumber: 'INS-2024-BER-005',
      insuranceCoverageAmount: '2000000',
      verificationStatus: 'verified' as const,
      kycCompleted: true,
      kycVerifiedAt: new Date('2023-11-20'),
      averageRating: '4.91',
      totalWalks: 956,
      totalReviews: 287,
      acceptanceRate: '97.2',
      responseTimeMinutes: 9,
      onTimeRate: '98.0',
      baseHourlyRate: '100.00',
      currency: 'ILS',
      isAvailable: true,
      maxDailyWalks: 8,
      bankAccountVerified: true,
      commissionRate: '18.00',
      isActive: true,
      hasBodyCamera: true,
      hasDroneAccess: true,
      maxSimultaneousDogs: 5,
      createdAt: new Date('2023-04-10'),
      updatedAt: new Date(),
    },
    {
      walkerId: `WALKER-${crypto.randomUUID()}`,
      userId: `user-${Date.now()}-6`,
      firstName: 'Shira',
      lastName: 'Goldstein',
      displayName: 'Shira G.',
      profilePhotoUrl: null,
      bio: 'Dedicated walker with background in animal shelter work. Experience with all breeds and temperaments. I treat every dog like family and provide lots of love and attention. Available for mid-day walks and puppy potty breaks. Flexible scheduling!',
      city: 'Tel Aviv',
      country: 'Israel',
      currentLatitude: '32.0853',
      currentLongitude: '34.7818',
      emergencyContactName: 'Michael Goldstein',
      emergencyContactPhone: '+972501234572',
      languagesSpoken: ['Hebrew', 'English'],
      experienceYears: 4,
      petSizesHandled: ['Small (0-10kg)', 'Medium (10-25kg)', 'Large (25-45kg)'],
      specialties: ['Puppy Training', 'Senior Dogs', 'Multiple Dogs'],
      certifications: ['Pet First Aid', 'Shelter Volunteer'],
      hasInsurance: true,
      insurancePolicyNumber: 'INS-2024-TEL-006',
      insuranceCoverageAmount: '2000000',
      verificationStatus: 'verified' as const,
      kycCompleted: true,
      kycVerifiedAt: new Date('2024-03-01'),
      averageRating: '4.89',
      totalWalks: 398,
      totalReviews: 142,
      acceptanceRate: '95.5',
      responseTimeMinutes: 15,
      onTimeRate: '96.8',
      baseHourlyRate: '70.00',
      currency: 'ILS',
      isAvailable: true,
      maxDailyWalks: 6,
      bankAccountVerified: true,
      commissionRate: '18.00',
      isActive: true,
      hasBodyCamera: false,
      hasDroneAccess: false,
      maxSimultaneousDogs: 3,
      createdAt: new Date('2024-01-05'),
      updatedAt: new Date(),
    },
    {
      walkerId: `WALKER-${crypto.randomUUID()}`,
      userId: `user-${Date.now()}-7`,
      firstName: 'Amit',
      lastName: 'Shapira',
      displayName: 'Amit S.',
      profilePhotoUrl: null,
      bio: 'Professional walker and adventure guide! I organize group dog walks and beach outings. Experience with social dogs who love playing with others. Weekend beach trips and park meetups available. Your dog will make new friends!',
      city: 'Herzliya',
      country: 'Israel',
      currentLatitude: '32.1624',
      currentLongitude: '34.8098',
      emergencyContactName: 'Liora Shapira',
      emergencyContactPhone: '+972501234573',
      languagesSpoken: ['Hebrew', 'English', 'Spanish'],
      experienceYears: 5,
      petSizesHandled: ['Small (0-10kg)', 'Medium (10-25kg)', 'Large (25-45kg)'],
      specialties: ['Multiple Dogs', 'Off-Leash', 'Jogging/Running'],
      certifications: ['Pet First Aid', 'Group Walking Specialist'],
      hasInsurance: true,
      insurancePolicyNumber: 'INS-2024-HRZ-007',
      insuranceCoverageAmount: '2000000',
      verificationStatus: 'verified' as const,
      kycCompleted: true,
      kycVerifiedAt: new Date('2024-02-10'),
      averageRating: '4.93',
      totalWalks: 567,
      totalReviews: 198,
      acceptanceRate: '96.8',
      responseTimeMinutes: 11,
      onTimeRate: '97.5',
      baseHourlyRate: '80.00',
      currency: 'ILS',
      isAvailable: true,
      maxDailyWalks: 6,
      bankAccountVerified: true,
      commissionRate: '18.00',
      isActive: true,
      hasBodyCamera: true,
      hasDroneAccess: false,
      maxSimultaneousDogs: 6,
      createdAt: new Date('2023-08-15'),
      updatedAt: new Date(),
    },
    {
      walkerId: `WALKER-${crypto.randomUUID()}`,
      userId: `user-${Date.now()}-8`,
      firstName: 'Tali',
      lastName: 'Ben-David',
      displayName: 'Tali B.',
      profilePhotoUrl: null,
      bio: 'Experienced walker specializing in small breeds and toy dogs. Gentle handling and lots of patience for nervous pups. I provide short, frequent walks perfect for small legs. Available for senior dogs needing slow, calm walks. Medication administration certified.',
      city: 'Ramat Gan',
      country: 'Israel',
      currentLatitude: '32.0809',
      currentLongitude: '34.8237',
      emergencyContactName: 'Yossi Ben-David',
      emergencyContactPhone: '+972501234574',
      languagesSpoken: ['Hebrew', 'English'],
      experienceYears: 6,
      petSizesHandled: ['Small (0-10kg)', 'Medium (10-25kg)'],
      specialties: ['Senior Dogs', 'Puppy Training', 'Reactive Dogs'],
      certifications: ['Pet First Aid', 'Pet Medication Administration'],
      hasInsurance: true,
      insurancePolicyNumber: 'INS-2024-RGN-008',
      insuranceCoverageAmount: '2000000',
      verificationStatus: 'verified' as const,
      kycCompleted: true,
      kycVerifiedAt: new Date('2024-01-25'),
      averageRating: '4.96',
      totalWalks: 689,
      totalReviews: 223,
      acceptanceRate: '98.2',
      responseTimeMinutes: 8,
      onTimeRate: '99.0',
      baseHourlyRate: '75.00',
      currency: 'ILS',
      isAvailable: true,
      maxDailyWalks: 7,
      bankAccountVerified: true,
      commissionRate: '18.00',
      isActive: true,
      hasBodyCamera: true,
      hasDroneAccess: false,
      maxSimultaneousDogs: 3,
      createdAt: new Date('2023-06-28'),
      updatedAt: new Date(),
    },
    {
      walkerId: `WALKER-${crypto.randomUUID()}`,
      userId: `user-${Date.now()}-9`,
      firstName: 'Ron',
      lastName: 'Avraham',
      displayName: 'Ron A.',
      profilePhotoUrl: null,
      bio: 'Tech-savvy walker with drone monitoring capabilities! I provide premium walks with aerial footage and real-time GPS tracking. Perfect for owners who want complete visibility. Experience with all breeds and comprehensive walk reports with photos and videos.',
      city: 'Tel Aviv',
      country: 'Israel',
      currentLatitude: '32.0853',
      currentLongitude: '34.7818',
      emergencyContactName: 'Rina Avraham',
      emergencyContactPhone: '+972501234575',
      languagesSpoken: ['Hebrew', 'English', 'Russian'],
      experienceYears: 4,
      petSizesHandled: ['Small (0-10kg)', 'Medium (10-25kg)', 'Large (25-45kg)', 'Giant (45kg+)'],
      specialties: ['Multiple Dogs', 'Off-Leash', 'Jogging/Running'],
      certifications: ['Pet First Aid', 'Drone Pilot License'],
      hasInsurance: true,
      insurancePolicyNumber: 'INS-2024-TEL-009',
      insuranceCoverageAmount: '2000000',
      verificationStatus: 'verified' as const,
      kycCompleted: true,
      kycVerifiedAt: new Date('2024-02-15'),
      averageRating: '4.94',
      totalWalks: 445,
      totalReviews: 167,
      acceptanceRate: '97.5',
      responseTimeMinutes: 6,
      onTimeRate: '98.8',
      baseHourlyRate: '110.00',
      currency: 'ILS',
      isAvailable: true,
      maxDailyWalks: 5,
      bankAccountVerified: true,
      commissionRate: '18.00',
      isActive: true,
      hasBodyCamera: true,
      hasDroneAccess: true,
      maxSimultaneousDogs: 4,
      createdAt: new Date('2023-10-12'),
      updatedAt: new Date(),
    },
    {
      walkerId: `WALKER-${crypto.randomUUID()}`,
      userId: `user-${Date.now()}-10`,
      firstName: 'Lior',
      lastName: 'Friedman',
      displayName: 'Lior F.',
      profilePhotoUrl: null,
      bio: 'Experienced walker and dog trainer specializing in behavior modification. I turn reactive dogs into calm walkers through consistent training and positive reinforcement. Former military dog handler with expertise in discipline and structure.',
      city: 'Netanya',
      country: 'Israel',
      currentLatitude: '32.3332',
      currentLongitude: '34.8530',
      emergencyContactName: 'Osnat Friedman',
      emergencyContactPhone: '+972501234576',
      languagesSpoken: ['Hebrew', 'English'],
      experienceYears: 9,
      petSizesHandled: ['Medium (10-25kg)', 'Large (25-45kg)', 'Giant (45kg+)'],
      specialties: ['Reactive Dogs', 'Multiple Dogs', 'Off-Leash'],
      certifications: ['Pet First Aid', 'Professional Dog Trainer', 'Behavior Specialist'],
      hasInsurance: true,
      insurancePolicyNumber: 'INS-2024-NET-010',
      insuranceCoverageAmount: '2000000',
      verificationStatus: 'verified' as const,
      kycCompleted: true,
      kycVerifiedAt: new Date('2023-12-01'),
      averageRating: '4.95',
      totalWalks: 812,
      totalReviews: 271,
      acceptanceRate: '98.5',
      responseTimeMinutes: 7,
      onTimeRate: '99.3',
      baseHourlyRate: '105.00',
      currency: 'ILS',
      isAvailable: true,
      maxDailyWalks: 6,
      bankAccountVerified: true,
      commissionRate: '18.00',
      isActive: true,
      hasBodyCamera: true,
      hasDroneAccess: false,
      maxSimultaneousDogs: 4,
      createdAt: new Date('2023-05-01'),
      updatedAt: new Date(),
    },
    {
      walkerId: `WALKER-${crypto.randomUUID()}`,
      userId: `user-${Date.now()}-11`,
      firstName: 'Dana',
      lastName: 'Katz',
      displayName: 'Dana K.',
      profilePhotoUrl: null,
      bio: 'Caring walker with veterinary technician background. I can handle dogs with special medical needs and administer medications during walks. Perfect for dogs recovering from surgery or with chronic conditions needing extra attention.',
      city: 'Petah Tikva',
      country: 'Israel',
      currentLatitude: '32.0889',
      currentLongitude: '34.8886',
      emergencyContactName: 'Guy Katz',
      emergencyContactPhone: '+972501234577',
      languagesSpoken: ['Hebrew', 'English', 'French'],
      experienceYears: 7,
      petSizesHandled: ['Small (0-10kg)', 'Medium (10-25kg)', 'Large (25-45kg)'],
      specialties: ['Senior Dogs', 'Puppy Training', 'Reactive Dogs'],
      certifications: ['Pet First Aid', 'Veterinary Technician', 'Pet Medication Administration'],
      hasInsurance: true,
      insurancePolicyNumber: 'INS-2024-PTK-011',
      insuranceCoverageAmount: '2000000',
      verificationStatus: 'verified' as const,
      kycCompleted: true,
      kycVerifiedAt: new Date('2024-01-08'),
      averageRating: '4.97',
      totalWalks: 623,
      totalReviews: 211,
      acceptanceRate: '97.8',
      responseTimeMinutes: 10,
      onTimeRate: '98.5',
      baseHourlyRate: '90.00',
      currency: 'ILS',
      isAvailable: true,
      maxDailyWalks: 5,
      bankAccountVerified: true,
      commissionRate: '18.00',
      isActive: true,
      hasBodyCamera: true,
      hasDroneAccess: false,
      maxSimultaneousDogs: 2,
      createdAt: new Date('2023-07-10'),
      updatedAt: new Date(),
    },
    {
      walkerId: `WALKER-${crypto.randomUUID()}`,
      userId: `user-${Date.now()}-12`,
      firstName: 'Ariel',
      lastName: 'Rosenberg',
      displayName: 'Ariel R.',
      profilePhotoUrl: null,
      bio: 'Adventure-loving walker specializing in hiking and trail walks! I take dogs on exciting outdoor adventures in nature reserves and forests. Perfect for high-energy dogs who need mental and physical stimulation. Weekend hiking trips available!',
      city: 'Haifa',
      country: 'Israel',
      currentLatitude: '32.7940',
      currentLongitude: '34.9896',
      emergencyContactName: 'Nurit Rosenberg',
      emergencyContactPhone: '+972501234578',
      languagesSpoken: ['Hebrew', 'English', 'German'],
      experienceYears: 6,
      petSizesHandled: ['Medium (10-25kg)', 'Large (25-45kg)', 'Giant (45kg+)'],
      specialties: ['Off-Leash', 'Jogging/Running', 'Multiple Dogs'],
      certifications: ['Pet First Aid', 'Wilderness First Responder', 'Trail Guide'],
      hasInsurance: true,
      insurancePolicyNumber: 'INS-2024-HFA-012',
      insuranceCoverageAmount: '2000000',
      verificationStatus: 'verified' as const,
      kycCompleted: true,
      kycVerifiedAt: new Date('2024-02-05'),
      averageRating: '4.92',
      totalWalks: 534,
      totalReviews: 184,
      acceptanceRate: '96.2',
      responseTimeMinutes: 12,
      onTimeRate: '97.0',
      baseHourlyRate: '95.00',
      currency: 'ILS',
      isAvailable: true,
      maxDailyWalks: 5,
      bankAccountVerified: true,
      commissionRate: '18.00',
      isActive: true,
      hasBodyCamera: true,
      hasDroneAccess: true,
      maxSimultaneousDogs: 4,
      createdAt: new Date('2023-08-22'),
      updatedAt: new Date(),
    },
  ];

  try {
    for (const walker of walkers) {
      await db.insert(walkerProfiles).values(walker).onConflictDoNothing();
    }
    console.log('[Seed] ✅ Successfully seeded 12 detailed walker profiles');
  } catch (error) {
    console.error('[Seed] ❌ Failed to seed walkers:', error);
    throw error;
  }
};

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  seedWalkers()
    .then(() => {
      console.log('[Seed] Walker seeding complete');
      process.exit(0);
    })
    .catch((error) => {
      console.error('[Seed] Walker seeding failed:', error);
      process.exit(1);
    });
}
