// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/invoice/BookingInvoice.tsx": () => import("../components/mockups/invoice/BookingInvoice.tsx"),
  "./components/mockups/invoice/GiftCardInvoice.tsx": () => import("../components/mockups/invoice/GiftCardInvoice.tsx")
};
