#!/usr/bin/env tsx
/**
 * Environment Variable Sanity Check
 * Verifies presence of required secrets WITHOUT logging their values
 * Run at server startup to catch missing credentials early.
 *
 * IMPORTANT: this is a hand-curated boot list. The full auto-generated
 * inventory lives at docs/PRODUCTION_REQUIRED_ENV_VARS.md (regenerated by
 * scripts/audit-required-env-vars.ts). Keep this list in sync with the
 * fail-closed guards in the corresponding code paths.
 *
 * Behavior:
 *   • In production (NODE_ENV=production): fail-boot (exit 1) on any missing
 *     REQUIRED var.
 *   • Elsewhere: warn only. Dev machines should be able to boot with an
 *     incomplete .env without the CLI aborting.
 */

interface EnvCheck {
  key: string;
  required: boolean;
  category: string;
  /** Optional alternate names accepted in lieu of `key` (any one satisfies the check). */
  alternates?: string[];
}

const ENV_CHECKS: EnvCheck[] = [
  // Core Infrastructure
  { key: 'DATABASE_URL', required: true, category: 'Database' },
  { key: 'SESSION_SECRET', required: true, category: 'Security' },
  { key: 'COOKIE_SECRET', required: true, category: 'Security' },

  // Auth / HMAC secrets — every one of these had a fail-closed guard added
  // in server code. Keep this list aligned with those guards.
  { key: 'JWT_SECRET', required: true, category: 'Security' },
  { key: 'KYC_SALT', required: true, category: 'Security' },
  { key: 'WALLET_LINK_SECRET', required: true, category: 'Security' },
  { key: 'MOBILE_LINK_SECRET', required: true, category: 'Security' },
  { key: 'QR_SECRET', required: true, category: 'Security' },
  { key: 'DOCUMENT_ENCRYPTION_KEY', required: true, category: 'Security' },
  { key: 'IP_HASH_SALT', required: true, category: 'Security' },
  // OTP HMAC storage — either alternate satisfies TwilioSMSService.
  { key: 'APP_SESSION_SECRET', required: true, category: 'Security', alternates: ['COOKIE_SECRET'] },

  // Firebase
  { key: 'FIREBASE_SERVICE_ACCOUNT_KEY', required: true, category: 'Firebase' },
  { key: 'VITE_FIREBASE_API_KEY', required: true, category: 'Firebase' },
  { key: 'VITE_FIREBASE_APP_ID', required: true, category: 'Firebase' },

  // Monitoring
  { key: 'SENTRY_DSN', required: true, category: 'Monitoring' },
  { key: 'ALERTS_SLACK_WEBHOOK', required: true, category: 'Monitoring' },
  { key: 'METRICS_AUTH_TOKEN', required: true, category: 'Monitoring' },

  // Email & Messaging (WhatsApp via Meta, FCM for push)
  { key: 'SENDGRID_API_KEY', required: true, category: 'Email' },

  // Payments — required in production per payment-provider-mode gate.
  // NAYAX_TERMINAL_ID_MAIN is required for K9000 authorize/capture routing.
  { key: 'NAYAX_TERMINAL_ID_MAIN', required: false, category: 'Payments' },

  // OAuth Providers
  { key: 'TIKTOK_CLIENT_KEY', required: false, category: 'OAuth' },
  { key: 'TIKTOK_CLIENT_SECRET', required: false, category: 'OAuth' },
  { key: 'FACEBOOK_APP_ID', required: false, category: 'OAuth' },
  { key: 'FACEBOOK_APP_SECRET', required: false, category: 'OAuth' },
  { key: 'INSTAGRAM_CLIENT_ID', required: false, category: 'OAuth' },
  { key: 'INSTAGRAM_CLIENT_SECRET', required: false, category: 'OAuth' },

  // Payment & Business (optional — feature-flagged live per env)
  { key: 'NAYAX_API_KEY', required: false, category: 'Payments' },
  { key: 'HUBSPOT_PORTAL_ID', required: false, category: 'CRM' },
];

interface CheckResult {
  present: string[];
  missing: { required: string[]; optional: string[] };
  byCategory: Record<string, { present: number; total: number }>;
}

/** Pure classification, no logging — safe to unit-test. */
export function classifyEnvironment(env: NodeJS.ProcessEnv = process.env): CheckResult {
  const result: CheckResult = {
    present: [],
    missing: { required: [], optional: [] },
    byCategory: {},
  };
  for (const check of ENV_CHECKS) {
    const candidates = [check.key, ...(check.alternates ?? [])];
    const value = candidates
      .map(k => env[k])
      .find(v => !!v && v.trim().length > 0);
    const isPresent = !!value;

    if (!result.byCategory[check.category]) {
      result.byCategory[check.category] = { present: 0, total: 0 };
    }
    result.byCategory[check.category].total++;

    if (isPresent) {
      result.present.push(check.key);
      result.byCategory[check.category].present++;
    } else if (check.required) {
      result.missing.required.push(check.key);
    } else {
      result.missing.optional.push(check.key);
    }
  }
  return result;
}

/**
 * Runtime boot gate.
 *
 * Throws when NODE_ENV === 'production' and any REQUIRED var is missing.
 * Callable from server/index.ts before route registration.
 */
export function assertRequiredEnvOrThrow(
  env: NodeJS.ProcessEnv = process.env,
): void {
  const { missing } = classifyEnvironment(env);
  const isProd = env.NODE_ENV === 'production';
  if (isProd && missing.required.length > 0) {
    throw new Error(
      `[verify-env] Missing REQUIRED env vars in production: ${missing.required.join(
        ', ',
      )}. Refusing to boot.`,
    );
  }
}

function checkEnvironment(): void {
  console.log('\n🔍 Environment Variable Sanity Check\n');
  console.log('═'.repeat(60));

  const results = classifyEnvironment();

  // Report by category
  console.log('\n📊 Status by Category:\n');
  Object.entries(results.byCategory).forEach(([category, stats]) => {
    const percentage = Math.round((stats.present / stats.total) * 100);
    const icon = stats.present === stats.total ? '✅' : stats.present > 0 ? '⚠️' : '❌';
    console.log(`${icon} ${category.padEnd(15)} ${stats.present}/${stats.total} (${percentage}%)`);
  });

  const isProd = process.env.NODE_ENV === 'production';

  // Missing required variables (CRITICAL)
  if (results.missing.required.length > 0) {
    console.log('\n❌ CRITICAL: Missing Required Secrets:\n');
    results.missing.required.forEach(key => {
      console.log(`   • ${key}`);
    });
    console.log(
      isProd
        ? '\n⛔ Refusing to boot: production requires all REQUIRED secrets to be set.\n'
        : '\n⚠️  Non-production run — continuing without exit. Set these before deploy.\n',
    );
  }

  // Missing optional variables (WARNING)
  if (results.missing.optional.length > 0) {
    console.log('\n⚠️  Optional Features Disabled (missing secrets):\n');
    results.missing.optional.forEach(key => {
      console.log(`   • ${key}`);
    });
  }

  // Summary
  console.log('\n' + '═'.repeat(60));
  const totalPresent = results.present.length;
  const totalChecked = ENV_CHECKS.length;
  const percentage = Math.round((totalPresent / totalChecked) * 100);

  if (results.missing.required.length === 0) {
    console.log(`✅ All required secrets present (${totalPresent}/${totalChecked} total, ${percentage}%)`);
  } else {
    console.log(`❌ Missing ${results.missing.required.length} required secret(s)`);
    if (isProd) {
      process.exit(1); // Fail-boot only in production
    }
  }

  console.log('═'.repeat(60) + '\n');
}

// CLI entry — only runs when the file is executed directly, not when
// imported by a test or by server/index.ts.
const isDirectRun =
  typeof process !== 'undefined' &&
  Array.isArray(process.argv) &&
  process.argv[1] &&
  /verify-env\.(t|j)s$/.test(process.argv[1]);

if (isDirectRun) {
  checkEnvironment();
}
