/**
 * PetWash™ Document Resolver
 *
 * Decides WHICH documents need to be generated for a given payment event.
 * This is the single authoritative source for document issuance logic.
 *
 * RULES:
 * 1. Booking confirmation  → always, immediately on booking_created
 * 2. Receipt               → when payment is CAPTURED (money received)
 *                            — must come from certified accounting system
 * 3. Tax invoice           → when a VAT event occurs (service delivered)
 *                            — must come from certified accounting system
 *                            — may require allocation number for B2B above threshold
 * 4. Escrow statement      → when funds change escrow state (held / released / refunded)
 * 5. Payout statement      → when provider payout is released
 * 6. Refund statement      → when any refund or partial refund occurs
 * 7. Credit note           → when a tax invoice is corrected/voided
 *
 * NEVER mix these documents.
 * NEVER generate receipt/tax_invoice from our own PDF system.
 */

import {
  requiresAllocationNumberFromAgorot,
} from "./LegalThresholdConfig";
import { logger } from "../lib/logger";
import type { DocumentPurpose, PaymentFlowStatus } from "@shared/schema-billing";

export type IssuingEntity = "platform" | "provider";
export type DocumentSystem = "internal_pdf" | "accounting_system";

export interface DocumentDecision {
  purpose: DocumentPurpose;
  issuingEntity: IssuingEntity;
  system: DocumentSystem;
  requiresAllocationNumber: boolean;
  notes: string;
}

export interface ResolverContext {
  bookingId: string;
  customerId?: string;
  providerId?: string;

  isB2B: boolean;
  customerTaxId?: string;

  /** Amount before VAT, in AGOROT */
  subtotalAgorot: number;
  /** Full gross amount captured from customer, in AGOROT */
  totalAgorot: number;
  /** Platform fee before VAT, in AGOROT */
  platformFeeAgorot?: number;
  /** Provider portion, in AGOROT */
  providerPayoutAgorot?: number;

  paymentFlowStatus: PaymentFlowStatus;
  issueDate?: Date;

  /** Used to determine VAT issuing entity */
  commercialModel: "MARKETPLACE_COMMISSION" | "PRINCIPAL";
}

export function resolveDocuments(ctx: ResolverContext): DocumentDecision[] {
  const decisions: DocumentDecision[] = [];
  const issueDate = ctx.issueDate ?? new Date();

  const needsAllocation = requiresAllocationNumberFromAgorot(
    ctx.subtotalAgorot,
    ctx.isB2B,
    issueDate
  );

  // ── 1. Booking confirmation ─────────────────────────────────────────────────
  // Always generated by us as an internal PDF.  Non-tax document.
  decisions.push({
    purpose:                  "booking_confirmation",
    issuingEntity:            "platform",
    system:                   "internal_pdf",
    requiresAllocationNumber: false,
    notes:
      "Service summary for customer. Non-tax document. " +
      "Must not be labelled as invoice, receipt, or קבלה.",
  });

  // ── 2. Receipt (קבלה) ────────────────────────────────────────────────────────
  // Generated ONLY when payment is captured. Must come from accounting system.
  if (
    ctx.paymentFlowStatus === "captured" ||
    ctx.paymentFlowStatus === "held_in_escrow" ||
    ctx.paymentFlowStatus === "released"
  ) {
    decisions.push({
      purpose:                  "receipt",
      issuingEntity:            "platform",   // platform receives the money
      system:                   "accounting_system",
      requiresAllocationNumber: false,        // receipts don't need allocation numbers
      notes:
        "קבלה — proof money received. " +
        "MUST be issued through certified Israeli accounting system. " +
        "Sequential numbering required. Cannot be a PDF we generate ourselves.",
    });
  }

  // ── 3. Tax invoice (חשבונית מס) ─────────────────────────────────────────────
  // Generated when the service is delivered (VAT event).
  // Issuing entity depends on commercial model.
  if (
    ctx.paymentFlowStatus === "released" ||
    ctx.paymentFlowStatus === "captured"
  ) {
    let issuingEntity: IssuingEntity;
    let taxInvoiceNotes: string;

    if (ctx.commercialModel === "PRINCIPAL") {
      // PetWash is the seller — platform issues the tax invoice to customer
      issuingEntity = "platform";
      taxInvoiceNotes =
        "PRINCIPAL model: PetWash issues חשבונית מס to customer. " +
        "Provider receives separate commission invoice or service order. " +
        "Must come from certified accounting system.";
    } else {
      // MARKETPLACE_COMMISSION: provider is the real supplier
      // Provider issues their own חשבונית מס to customer (or to platform depending on structure)
      issuingEntity = "provider";
      taxInvoiceNotes =
        "MARKETPLACE_COMMISSION model: Provider issues חשבונית מס. " +
        "Platform issues separate commission invoice to provider. " +
        "Both must come from certified accounting systems.";
    }

    decisions.push({
      purpose:                  "tax_invoice",
      issuingEntity,
      system:                   "accounting_system",
      requiresAllocationNumber: needsAllocation,
      notes:                    taxInvoiceNotes,
    });

    if (needsAllocation) {
      logger.warn("[DocumentResolver] Tax invoice requires ITA allocation number", {
        bookingId:     ctx.bookingId,
        subtotalNIS:   (ctx.subtotalAgorot / 100).toFixed(2),
        isB2B:         ctx.isB2B,
        customerTaxId: ctx.customerTaxId,
      });
    }
  }

  // ── 4. Escrow statement ──────────────────────────────────────────────────────
  const escrowStates: PaymentFlowStatus[] = [
    "captured", "held_in_escrow", "released", "refunded",
    "partially_refunded", "disputed", "chargeback",
  ];
  if (escrowStates.includes(ctx.paymentFlowStatus) && ctx.providerId) {
    decisions.push({
      purpose:                  "escrow_statement",
      issuingEntity:            "platform",
      system:                   "internal_pdf",
      requiresAllocationNumber: false,
      notes:
        "Internal money flow document for provider and ops. " +
        "Shows: captured, platform fee, VAT on fee, held/released amounts. " +
        "Non-tax document. Must not be labelled as invoice or receipt.",
    });
  }

  // ── 5. Payout statement ──────────────────────────────────────────────────────
  if (ctx.paymentFlowStatus === "released" && ctx.providerId) {
    decisions.push({
      purpose:                  "payout_statement",
      issuingEntity:            "platform",
      system:                   "internal_pdf",
      requiresAllocationNumber: false,
      notes:
        "Shows provider net payout breakdown after platform fee deduction. " +
        "Supports provider reconciliation. Non-tax document.",
    });
  }

  // ── 6. Refund statement ──────────────────────────────────────────────────────
  if (
    ctx.paymentFlowStatus === "refunded" ||
    ctx.paymentFlowStatus === "partially_refunded"
  ) {
    decisions.push({
      purpose:                  "refund_statement",
      issuingEntity:            "platform",
      system:                   "internal_pdf",
      requiresAllocationNumber: false,
      notes:
        "Reversal/adjustment document. " +
        "If a tax invoice was already issued, a credit note must also be issued " +
        "through the certified accounting system.",
    });

    if (ctx.paymentFlowStatus === "refunded") {
      decisions.push({
        purpose:                  "credit_note",
        issuingEntity:            "platform",
        system:                   "accounting_system",
        requiresAllocationNumber: false,
        notes:
          "Credit note (זיכוי) to offset any already-issued tax invoice. " +
          "Must come from certified accounting system. Sequential numbering required.",
      });
    }
  }

  logger.info("[DocumentResolver] Documents resolved", {
    bookingId:    ctx.bookingId,
    status:       ctx.paymentFlowStatus,
    isB2B:        ctx.isB2B,
    needsAlloc:   needsAllocation,
    docCount:     decisions.length,
    purposes:     decisions.map(d => d.purpose),
  });

  return decisions;
}

/** Quick summary for logging / API responses */
export function summarizeDecisions(decisions: DocumentDecision[]): string {
  return decisions
    .map(d => `${d.purpose}(${d.system})${d.requiresAllocationNumber ? "[ALLOC]" : ""}`)
    .join(", ");
}
