/**
 * BookingConfirmationViewer
 *
 * Displays a booking confirmation / service summary for the customer.
 *
 * WHAT THIS IS:
 *   - A service record showing what was booked, who the provider is,
 *     and the payment status. For customer reference only.
 *
 * WHAT THIS IS NOT:
 *   - NOT a tax invoice (חשבונית מס)
 *   - NOT a receipt (קבלה)
 *   - NOT a legal financial document of any kind
 *
 * Legal receipts and tax invoices are issued separately through the
 * certified Israeli accounting system. They are NOT generated by this UI.
 *
 * Previously named "IsraeliTaxInvoice" — renamed to prevent legal confusion.
 * The component name is kept as an alias for backwards compatibility with
 * existing import sites, but the rendered content is a booking confirmation only.
 */

import { useRef } from 'react';
import { Button } from '@/components/ui/button';
import { Printer, AlertTriangle } from 'lucide-react';

export interface InvoiceLineItem {
  description: string;
  descriptionHe?: string;
  quantity: number;
  unitPrice: number;
  total: number;
}

export interface IsraeliInvoiceData {
  /** Internal booking reference — NOT an invoice number */
  invoiceNumber: string;
  /** Do not use — kept for interface compatibility only. Not rendered. */
  invoiceType?: string;
  issueDate: string;
  bookingId?: string;
  paymentMethod?: string;
  paymentMethodHe?: string;
  transactionId?: string;

  supplierName: string;
  supplierNameHe?: string;
  supplierVatNumber: string;
  supplierAddress: string;
  supplierAddressHe?: string;
  supplierPhone?: string;
  supplierEmail?: string;

  customerName: string;
  customerPhone?: string;
  customerEmail?: string;
  customerVatNumber?: string;
  customerAddress?: string;

  lineItems: InvoiceLineItem[];

  subtotalBeforeVat: number;
  vatRate: number;
  vatAmount: number;
  totalWithVat: number;
  discountAmount?: number;
  loyaltyPointsEarned?: number;
  notes?: string;
  notesHe?: string;
}

interface Props {
  data: IsraeliInvoiceData;
  language?: 'he' | 'en';
  showActions?: boolean;
}

/**
 * Booking Confirmation Viewer
 * Exported as IsraeliTaxInvoice for backwards compatibility.
 * Renders a booking confirmation only — not a tax document.
 */
export function IsraeliTaxInvoice({ data, language = 'he', showActions = true }: Props) {
  const confirmationRef = useRef<HTMLDivElement>(null);
  const isHebrew = language === 'he';

  const fmt = (n: number) =>
    new Intl.NumberFormat('he-IL', { style: 'currency', currency: 'ILS', minimumFractionDigits: 2 }).format(n);

  const issueDateFormatted = new Date(data.issueDate).toLocaleDateString('he-IL', {
    day: '2-digit', month: '2-digit', year: 'numeric'
  });

  const handlePrint = () => {
    const el = confirmationRef.current;
    if (!el) return;
    const w = window.open('', '_blank');
    if (!w) return;
    w.document.write(`
      <!DOCTYPE html>
      <html dir="rtl" lang="he">
      <head>
        <meta charset="utf-8"/>
        <title>${isHebrew ? 'אישור הזמנה' : 'Booking Confirmation'} — ${data.invoiceNumber}</title>
        <style>
          * { box-sizing: border-box; margin: 0; padding: 0; }
          body { font-family: Arial, sans-serif; background: white; color: #111; font-size: 13px; }
          .wrap { max-width: 800px; margin: 0 auto; padding: 32px; }
          .notice { background:#ffffff;border:1.5px solid #F0A500;border-radius:8px;padding:12px 16px;margin-bottom:20px;font-size:11px;color:#000000; }
          @media print { body { print-color-adjust: exact; } }
        </style>
      </head>
      <body>
        <div class="wrap">
          <div class="notice">
            ⚠️ ${isHebrew
              ? 'מסמך זה הוא אישור הזמנה בלבד. אינו חשבונית מס, קבלה, או מסמך מס חוקי. מסמכי מס חוקיים יונפקו בנפרד דרך מערכת הנה"ח המאושרת.'
              : 'This document is a BOOKING CONFIRMATION only. It is NOT a tax invoice, receipt, or any legal financial document. Legal tax documents are issued separately through the certified accounting system.'}
          </div>
          ${el.innerHTML}
        </div>
      </body>
      </html>
    `);
    w.document.close();
    setTimeout(() => { w.focus(); w.print(); }, 400);
  };

  return (
    <div className="space-y-3">

      {/* Legal disclaimer — always visible */}
      <div className="flex gap-2 items-start rounded-xl border border-amber-300 bg-amber-50 px-4 py-3 text-sm text-amber-800">
        <AlertTriangle className="w-4 h-4 mt-0.5 shrink-0 text-amber-500" />
        <span>
          {isHebrew
            ? 'זהו אישור הזמנה בלבד — לא חשבונית מס ולא קבלה. מסמכי מס רשמיים יונפקו בנפרד דרך מערכת הנה"ח המאושרת.'
            : 'This is a BOOKING CONFIRMATION only — not a tax invoice and not a receipt. Official tax documents are issued separately through the certified accounting system.'}
        </span>
      </div>

      {showActions && (
        <div className="flex gap-2 flex-wrap">
          <Button
            onClick={handlePrint}
            style={{ background: '#1A1A1A' }}
            className="text-white rounded-xl gap-2 text-sm font-semibold"
          >
            <Printer className="w-4 h-4" />
            {isHebrew ? 'הדפס אישור הזמנה' : 'Print Booking Confirmation'}
          </Button>
        </div>
      )}

      {/* Booking Confirmation */}
      <div
        ref={confirmationRef}
        dir="rtl"
        className="bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden"
        style={{ fontFamily: 'Arial, sans-serif', maxWidth: 800 }}
      >
        {/* Header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', borderBottom: '3px solid #1A1A1A', padding: '24px 32px 20px', background: '#fff' }}>
          <div>
            <h1 style={{ fontSize: 28, fontWeight: 900, letterSpacing: -1, color: '#000' }}>PetWash™</h1>
            <p style={{ fontSize: 11, color: '#555', marginTop: 2 }}>פט וואש בע"מ — ח.פ. 517145033</p>
            <p style={{ fontSize: 10, color: '#999', marginTop: 2 }}>www.petwash.co.il</p>
          </div>
          <div style={{ textAlign: 'left' }}>
            <h2 style={{ fontSize: 20, fontWeight: 700, color: '#000' }}>
              {isHebrew ? 'אישור הזמנה' : 'Booking Confirmation'}
            </h2>
            <p style={{ fontSize: 10, color: '#888', marginTop: 3 }}>
              {isHebrew ? 'מסמך שירות — לא חשבונית מס' : 'Service record — NOT a tax document'}
            </p>
            <p style={{ fontFamily: 'monospace', fontSize: 13, color: '#333', marginTop: 6 }}>
              {isHebrew ? 'אסמכתא:' : 'Ref:'} {data.invoiceNumber}
            </p>
            <p style={{ fontSize: 11, color: '#777', marginTop: 3 }}>{issueDateFormatted}</p>
            {data.bookingId && <p style={{ fontSize: 10, color: '#aaa', marginTop: 2 }}>{isHebrew ? 'הזמנה:' : 'Booking:'} {data.bookingId}</p>}
          </div>
        </div>

        <div style={{ padding: '20px 32px' }}>

          {/* Parties */}
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20, marginBottom: 24, padding: 16, background: '#f9f9f9', borderRadius: 10 }}>
            <div>
              <h3 style={{ fontSize: 10, fontWeight: 700, textTransform: 'uppercase', color: '#777', marginBottom: 8, letterSpacing: 1 }}>{isHebrew ? 'ספק השירות' : 'Service Provider'}</h3>
              <p style={{ fontSize: 14, fontWeight: 700 }}>{data.supplierNameHe || data.supplierName}</p>
              <p style={{ fontSize: 12, lineHeight: 1.6, color: '#444', whiteSpace: 'pre-line' }}>{data.supplierAddressHe || data.supplierAddress}</p>
              {data.supplierPhone && <p style={{ fontSize: 11, color: '#555', marginTop: 4 }}>📞 {data.supplierPhone}</p>}
              {data.supplierEmail && <p style={{ fontSize: 11, color: '#555' }}>✉ {data.supplierEmail}</p>}
            </div>
            <div>
              <h3 style={{ fontSize: 10, fontWeight: 700, textTransform: 'uppercase', color: '#777', marginBottom: 8, letterSpacing: 1 }}>{isHebrew ? 'לקוח' : 'Customer'}</h3>
              <p style={{ fontSize: 14, fontWeight: 700 }}>{data.customerName}</p>
              {data.customerAddress && <p style={{ fontSize: 12, lineHeight: 1.6, color: '#444' }}>{data.customerAddress}</p>}
              {data.customerPhone && <p style={{ fontSize: 11, color: '#555', marginTop: 4 }}>📞 {data.customerPhone}</p>}
              {data.customerEmail && <p style={{ fontSize: 11, color: '#555' }}>✉ {data.customerEmail}</p>}
            </div>
          </div>

          {/* Service items */}
          <table style={{ width: '100%', borderCollapse: 'collapse', marginBottom: 20 }}>
            <thead>
              <tr>
                <th style={{ background: '#1A1A1A', color: '#fff', padding: '10px 12px', fontSize: 12, textAlign: 'right' }}>{isHebrew ? 'תיאור' : 'Description'}</th>
                <th style={{ background: '#1A1A1A', color: '#fff', padding: '10px 12px', fontSize: 12, textAlign: 'center', width: 60 }}>{isHebrew ? 'כמות' : 'Qty'}</th>
                <th style={{ background: '#1A1A1A', color: '#fff', padding: '10px 12px', fontSize: 12, textAlign: 'left', width: 110 }}>{isHebrew ? 'מחיר' : 'Price'}</th>
                <th style={{ background: '#1A1A1A', color: '#fff', padding: '10px 12px', fontSize: 12, textAlign: 'left', width: 110 }}>{isHebrew ? 'סה"כ' : 'Total'}</th>
              </tr>
            </thead>
            <tbody>
              {data.lineItems.map((item, i) => (
                <tr key={i}>
                  <td style={{ padding: '10px 12px', fontSize: 13, borderBottom: '1px solid #eee', background: 'white' }}>{item.descriptionHe || item.description}</td>
                  <td style={{ padding: '10px 12px', fontSize: 13, textAlign: 'center', borderBottom: '1px solid #eee', background: 'white' }}>{item.quantity}</td>
                  <td style={{ padding: '10px 12px', fontSize: 13, textAlign: 'left', borderBottom: '1px solid #eee', background: 'white', fontFamily: 'monospace' }}>{fmt(item.unitPrice)}</td>
                  <td style={{ padding: '10px 12px', fontSize: 13, textAlign: 'left', borderBottom: '1px solid #eee', background: 'white', fontFamily: 'monospace', fontWeight: 600 }}>{fmt(item.total)}</td>
                </tr>
              ))}
            </tbody>
          </table>

          {/* Payment status summary (for reference only) */}
          <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
            <div style={{ width: 300 }}>
              <p style={{ fontSize: 10, color: '#888', marginBottom: 8, textAlign: 'left' }}>
                {isHebrew ? 'מצב תשלום — לעיון בלבד (לא מסמך מס)' : 'Payment status — for reference only (not a tax document)'}
              </p>
              <div style={{ display: 'flex', justifyContent: 'space-between', padding: '5px 0', fontSize: 13 }}>
                <span style={{ color: '#555' }}>{isHebrew ? 'לפני מע"מ:' : 'Before VAT:'}</span>
                <span style={{ fontFamily: 'monospace' }}>{fmt(data.subtotalBeforeVat)}</span>
              </div>
              {data.discountAmount && data.discountAmount > 0 && (
                <div style={{ display: 'flex', justifyContent: 'space-between', padding: '5px 0', fontSize: 13, color: '#16a34a' }}>
                  <span>{isHebrew ? 'הנחה:' : 'Discount:'}</span>
                  <span style={{ fontFamily: 'monospace' }}>−{fmt(data.discountAmount)}</span>
                </div>
              )}
              <div style={{ display: 'flex', justifyContent: 'space-between', padding: '6px 0', fontSize: 13, borderTop: '1px dashed #ccc', marginTop: 4, color: '#555' }}>
                <span>{isHebrew ? `מע"מ (${(data.vatRate * 100).toFixed(0)}%):` : `VAT (${(data.vatRate * 100).toFixed(0)}%):`}</span>
                <span style={{ fontFamily: 'monospace' }}>{fmt(data.vatAmount)}</span>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', padding: '10px 0', fontSize: 18, fontWeight: 900, borderTop: '3px solid #1A1A1A', marginTop: 4 }}>
                <span>{isHebrew ? 'סה"כ ששולם:' : 'Total paid:'}</span>
                <span style={{ fontFamily: 'monospace' }}>{fmt(data.totalWithVat)}</span>
              </div>
            </div>
          </div>

          {/* Payment details */}
          <div style={{ marginTop: 20, padding: 14, border: '1.5px solid #ddd', borderRadius: 8 }}>
            <p style={{ fontSize: 11, color: '#777', marginBottom: 4 }}>{isHebrew ? 'אמצעי תשלום:' : 'Payment method:'}</p>
            <p style={{ fontSize: 14, fontWeight: 700 }}>{data.paymentMethodHe || data.paymentMethod || (isHebrew ? 'כרטיס אשראי' : 'Credit card')}</p>
            {data.transactionId && <p style={{ fontSize: 10, color: '#999', fontFamily: 'monospace', marginTop: 2 }}>{isHebrew ? 'עסקה:' : 'Transaction:'} {data.transactionId}</p>}
          </div>

          {/* Notes */}
          {(data.notesHe || data.notes) && (
            <div style={{ marginTop: 14, padding: 12, background: '#ffffff', borderRadius: 8, fontSize: 12, color: '#000000' }}>
              <span style={{ fontWeight: 700 }}>{isHebrew ? 'הערות: ' : 'Notes: '}</span>
              {data.notesHe || data.notes}
            </div>
          )}

          {/* Loyalty */}
          {data.loyaltyPointsEarned && data.loyaltyPointsEarned > 0 && (
            <div style={{ marginTop: 10, padding: 10, background: '#f0fdf4', borderRadius: 8, fontSize: 12, color: '#166534' }}>
              🏆 {data.loyaltyPointsEarned} {isHebrew ? 'נקודות נצברו' : 'loyalty points earned'}
            </div>
          )}

          {/* Footer disclaimer */}
          <div style={{ marginTop: 20, padding: '12px 0', borderTop: '1px solid #eee', fontSize: 10, color: '#aaa', lineHeight: 1.7 }}>
            <p style={{ fontWeight: 700, color: '#F0A500', marginBottom: 4 }}>
              ⚠️ {isHebrew
                ? 'מסמך זה אינו חשבונית מס ואינו קבלה חוקית.'
                : 'This document is NOT a tax invoice and NOT a legal receipt.'}
            </p>
            <p>
              {isHebrew
                ? 'אישור הזמנה זה הוא מסמך פנימי לצרכי תיאום בלבד. חשבונית המס הרשמית ו/או הקבלה יונפקו בנפרד דרך מערכת הנהלת החשבונות המאושרת.'
                : 'This booking confirmation is an internal service record only. Official tax invoice and/or receipt are issued separately through the certified accounting system.'}
            </p>
            <p style={{ marginTop: 4 }}>
              PetWash Ltd. (פט וואש בע"מ) | ח.פ. 517145033 | www.petwash.co.il
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

/**
 * Build booking confirmation data from a transaction/booking object.
 *
 * IMPORTANT: invoiceNumber here is a BOOKING REFERENCE, not a legal invoice number.
 * Legal invoice numbers must come from the certified accounting system.
 */
export function buildInvoiceFromTransaction(
  tx: any,
  customerName: string,
  customerPhone?: string,
  customerEmail?: string
): IsraeliInvoiceData {
  const amount = parseFloat(tx.amount || tx.totalAmount || 0);
  const vatRate = 0.18;
  const subtotal = amount / (1 + vatRate);
  const vatAmount = amount - subtotal;

  // Use existing booking reference — never generate a fake invoice number
  const bookingRef = tx.bookingId || tx.id || tx.transactionId
    ? `REF-${(tx.bookingId || tx.id || tx.transactionId || '').toString().slice(-8).toUpperCase()}`
    : 'REF-PENDING';

  return {
    invoiceNumber: bookingRef,
    issueDate:     tx.createdAt || tx.completedAt || new Date().toISOString(),
    transactionId: tx.transactionId || tx.id,
    bookingId:     tx.bookingId,
    paymentMethod: tx.paymentMethod,
    paymentMethodHe:
      tx.paymentMethod === 'credit_card' ? 'כרטיס אשראי'
      : tx.paymentMethod === 'wallet'     ? 'ארנק PetWash'
      : tx.paymentMethod === 'cash'       ? 'מזומן'
      : tx.paymentMethod || 'כרטיס אשראי',

    supplierName:      'PetWash Ltd.',
    supplierNameHe:    'פט וואש בע"מ',
    supplierVatNumber: '517145033',
    supplierAddress:   'Israel',
    supplierAddressHe: 'ישראל',
    supplierPhone:     '*2637',
    supplierEmail:     'support@petwash.co.il',

    customerName,
    customerPhone,
    customerEmail,

    lineItems: tx.lineItems || [{
      description:   tx.serviceName   || tx.serviceType || 'Pet Care Service',
      descriptionHe: tx.serviceNameHe || tx.serviceType || 'שירות טיפוח לחיית מחמד',
      quantity:  1,
      unitPrice: subtotal,
      total:     subtotal,
    }],

    subtotalBeforeVat: subtotal,
    vatRate,
    vatAmount,
    totalWithVat:      amount,
    discountAmount:    tx.discountAmount,
    loyaltyPointsEarned: tx.loyaltyPointsEarned,
    notes:    tx.notes,
    notesHe:  tx.notesHe,
  };
}
